server-name: "&6&lUltra&fVanilla"
default-format: "<{name}> {message}"
ranked-format: "[{colored-rank}] <{name}> {message}"
default-rank: default
enable-chat-filter: true
suicide-message:
  - "%s committed suicide"
  - "%s took their own life"
motd:
  - "A Minecraft Server?"
  - "&eNow with a &bTRULY&f&e dedicated server!"
  - "&bWhat did you expect?"
  - "&duwu"
  - "&oCongradulations to &9%player&r&o...! R.I.P."
  - "&0Whatareyoulookingat"
  - "&6*Slaps server* this baby can get slapped"
  - "&oHello, epic department?"