# Groups
default-group: default
format:
  default: '&r<{name-color}{name}&r> {text-color}{message}'
  prefixed: '&7[{rank}&r&7]&r &7<&r{name-color}{name}&r&7> &r{text-color}{message}'

# Strings
strings:
  suicide-message:
    - '%s committed suicide'
    - '%s took their own life'
  private-message:
    to: '&7&oYou whisper to {recipient}: {message}'
    from: '&7&o{player} whispers to you: {message}'
    spy: '&8&o{player} whispers to {recipient}: {message}'

# MOTD
motd:
  server-name: '&6&lUltra&fVanilla'
  version-color: AQUA
  strings:
    - 'A Minecraft Server?'
    - '&bWhat did you expect?'
    - '&duwu'
    - '&oCongradulations to &9%player&r&o...!'
    - '&0Whatareyoulookingat'
    - '&oHello, epic department?'
    - 'Message of the day :)!'
    - '&bГде я в любом случае?'

# Colors
color:
  rank:
    member: YELLOW
    loyalist: GREEN
    donator: LIGHT_PURPLE
    helper: GRAY
    moderator: BLUE
    admin: RED
    owner: AQUA