default-rank: default
format:
  unranked: '&r<{name-color}{name}&r> {text-color}{message}'
  ranked: '&7[{rank}&r&7]&r &7<&r{name-color}{name}&r&7> &r{text-color}{message}'

# Chat Filter
enable-chat-filter: false
swears:
  fuck: [heck, frick]
  shit: [crap, crud, barnacles]
  nigger: [homie, noodle]
  bitch: [bunny, basket]
  faggot: [friend, buddy]
  dick: [richard]
  cock: [rooster]
  cunt: [cantaloupe]
  asshole: [silly goose, silly]
  pussy: [kitten]
  piss: [peepee]
  arsehole: [..lol]
  whore: [broad]
  god: [g*d]
  kike: [kite]
  nigga: [nibba]

# Suicide
strings:
  suicide-message:
    - '%s committed suicide'
    - '%s took their own life'
  private-message:
    to: '&7&oYou whisper to {recipient}: {message}'
    from: '&7&o{player} whispers to you: {message}'
    spy: '&8&o{player} whispers to {recipient}: {message}'

# MOTD
motd:
  server-name: '&6&lUltra&fVanilla'
  version-color: AQUA
  strings:
    - 'A Minecraft Server?'
    - '&bWhat did you expect?'
    - '&duwu'
    - '&oCongradulations to &9%player&r&o...!'
    - '&0Whatareyoulookingat'
    - '&oHello, epic department?'
    - 'Message of the day :)!'
    - '&bГде я в любом случае?'

# Colors
color:
  rank:
    member: YELLOW
    loyalist: GREEN
    donator: LIGHT_PURPLE
    helper: GRAY
    moderator: BLUE
    admin: RED
    owner: AQUA