default-format: "<{name}> {message}"
ranked-format: "[{colored-rank}] <{name}> {message}"
default-rank: default
enable-chat-filter: true
suicide-message:
  - "%s committed suicide"
  - "%s took their own life"
